### ISSUE TITLE
Cannot run the test script

### ISSUE THREAD

**Issue by Enigma-li** [HobbitLong/shape2prog#5]
Hi,

Very good work! I am now trying to run the test script as suggested, but it failed. Below are some steps to run, could you please help advise?

1. Install
   a. I use the docker with Ubuntu 16.04, CUDA 9.0, CUDNN 7.0
   b. I use conda to create the environment:
       conda create -n shapeprog python=3.5
       activate env
       pip install -r requirements.txt

2. Run the test script
    a. download data as suggested
    b. run the script: CUDA_VISIBLE_DEVICES=0 python test.py --model ./model/program_generator_GA_chair.t7 --data ./data/chair_testing.h5 --save_path ./output/chair/ --save_prog --save_img

3. Error message
    ========= arguments =========  
Test: epoch 0 batch 0/32, time=0.392
Test: epoch 0 batch 10/32, time=0.219
Test: epoch 0 batch 20/32, time=0.218
Test: epoch 0 batch 30/32, time=0.219
Mean IoU: 0.560
Traceback (most recent call last):
  File "test.py", line 177, in <module>
    run() 
  File "test.py", line 160, in run
    out.write(program) 
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 186: ordinal not in range

I have tried python 3.6, it gives the same error.

**Comment by aluo-x** [comment]
The problem is due to the use of the `\N{DEGREE SIGN}` in [interpreter.py](https://github.com/HobbitLong/shape2prog/blob/44ebb0c46148a7d3da77dcdfb28efe01d1884731/interpreter.py). 
You should be able to fix this by directly specifying the encoding when writing to the file at [test.py#L159](https://github.com/HobbitLong/shape2prog/blob/master/test.py#L159). 

Try modifying it so it is 
```with open(save_file, 'w', encoding='utf-8') as out:```

If that fails, you can try modifying [test.py#L160]:(https://github.com/HobbitLong/shape2prog/blob/master/test.py#L160)
```out.write(program.encode("ascii", "ignore"))```

I suspect that you have a python version error. In python 3 the encoding should default to utf-8.

**Comment by Enigma-li** [comment]
Thanks for your reply!

The python version is 3.5, thus it is so weird. let me first try the modification proposed by you

**Comment by Enigma-li** [comment]
BTW, if I install the environment as in README, the torch installation would give error that, the version is not available at the platform
